[package]
authors = ["jake champion <me@jakechampion.name>"]
edition = "2018"
name = "trash"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
exitcode = "1.1.2"
glob = "0.3.0"
trash = "1.2.0"
