on:
  push:
    tags:
      - "v*" # push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "armv7-unknown-linux-musleabihf"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: "trash-${{ matrix.target }}"
          path: "target/${{ matrix.target }}/release/trash"

  build-darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v2
        with:
          name: "trash-x86_64-apple-darwin"
          path: "target/x86_64-apple-darwin/release/trash"

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc
      - uses: actions/upload-artifact@v2
        with:
          name: "trash-x86_64-pc-windows-msvc"
          path: "target/x86_64-pc-windows-msvc/release/trash.exe"

  release-upload:
    needs:
      - build-linux
      - build-darwin
      - build-windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -lR

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "trash-x86_64-unknown-linux-gnu/trash"
          asset_name: "trash-x86_64-unknown-linux-gnu"
          asset_content_type: application/octet-stream

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "trash-x86_64-unknown-linux-musl/trash"
          asset_name: "trash-x86_64-unknown-linux-musl"
          asset_content_type: application/octet-stream

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "trash-armv7-unknown-linux-musleabihf/trash"
          asset_name: "trash-armv7-unknown-linux-musleabihf"
          asset_content_type: application/octet-stream

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "trash-x86_64-apple-darwin/trash"
          asset_name: "trash-x86_64-apple-darwin"
          asset_content_type: application/octet-stream

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "trash-x86_64-pc-windows-msvc/trash.exe"
          asset_name: "trash-x86_64-pc-windows-msvc.exe"
          asset_content_type: application/octet-stream
